from typing import List, Optional
from enum import Enum
from pydantic import BaseModel, Field, HttpUrl
from datetime import date

class ExperienceType(str, Enum):
    """Enumeration of experience types."""
    PROFESSIONAL = "Professional"
    ACADEMIC = "Academic"
    VOLUNTEER = "Volunteer"
    RESEARCH = "Research"

class FundingAgency(str, Enum):
    """Enumeration of funding agencies."""
    CIHR = "CIHR"
    FRQS = "FRQS"
    NSERC = "NSERC"

class UserProfile(BaseModel):
    """
    Represents a user's profile information.
    """
    full_name: Optional[str] = Field(None, description="User's full name")
    program_level: Optional[str] = Field(None, description="Current program level (e.g. PhD, Masters)")
    research_field: Optional[str] = Field(None, description="Broad field of research")
    research_focus: Optional[str] = Field(None, description="Specific research focus or topic")
    institution: Optional[str] = Field(None, description="Academic institution")

class Experience(BaseModel):
    """
    Represents a user's experience (professional, academic, etc.).
    """
    id: Optional[str] = Field(None, description="Unique identifier for the experience")
    type: ExperienceType = Field(..., description="Type of experience")
    title: str = Field(..., description="Title of the role or position")
    organization: str = Field(..., description="Organization or institution name")
    start_date: date = Field(..., description="Start date of the experience")
    end_date: Optional[date] = Field(None, description="End date (None if current)")
    description: str = Field(..., description="Detailed description of the experience")
    key_skills: List[str] = Field(default_factory=list, description="List of skills acquired")

class FundingDefinition(BaseModel):
    """
    Static information about a funding.
    """
    id: str = Field(..., description="Unique ID of the funding")
    name: str = Field(..., description="Name of the funding")
    agency: FundingAgency = Field(..., description="Funding agency")
    cycle_year: str = Field(..., description="Cycle year (e.g., 2025-2026)")
    deadline: date = Field(..., description="Application deadline")
    website_url: HttpUrl = Field(..., description="URL to the funding page")
    description: Optional[str] = Field(None, description="Detailed description/context of the funding")

class FundingVision(BaseModel):
    """
    Represents a funding agency's vision and mission.
    """
    agency: FundingAgency = Field(..., description="Funding agency")
    description: str = Field(..., description="Vision of the agency (includes objectives, values, mission, etc.)")

class StoryTellingRequest(BaseModel):
    """
    Request model for telling a story based on an experience.
    """
    experience: Experience = Field(..., description="The experience to use as a base")
    target_funding: FundingDefinition = Field(..., description="The target funding")

class ExperienceAnalysis(BaseModel):
    """
    Represents the experience_analysis table in Supabase.
    Stores LLM-generated analysis of experiences aligned with funding opportunities.
    Maps 1:1 with the experience_analysis SQL table schema.
    """
    id: Optional[str] = Field(None, description="UUID primary key (auto-generated by database)")
    user_id: str = Field(..., description="UUID of the user who owns this analysis")
    experience_id: str = Field(..., description="UUID of the experience being analyzed")
    funding_id: str = Field(..., description="UUID of the funding this analysis targets")
    story: str = Field(..., description="Rewritten description tailored to the funding agency's vision")
    rationale: str = Field(..., description="Rationale explaining the facet scores and rewriting approach")
    experience_rating_facet_a: int = Field(..., ge=1, le=5, description="Facet A: Competency & Capacity (1-5)")
    experience_rating_facet_b: int = Field(..., ge=1, le=5, description="Facet B: Fit with Program Priorities (1-5)")
    experience_rating_facet_c: int = Field(..., ge=1, le=5, description="Facet C: Impact & Value (1-5)")
    experience_rating_facet_d: int = Field(..., ge=1, le=5, description="Facet D: Narrative Flow & Coherence (1-5)")
    created_at: Optional[str] = Field(None, description="Timestamp when analysis was created (auto-generated)")

class StoryTellingResponse(BaseModel):
    """
    Response model for story-telling API (transient, not stored directly).
    Used for LLM responses, then transformed to ExperienceAnalysis for storage.
    """
    experience_id: Optional[str] = Field(None, description="ID of the original experience")
    story: str = Field(..., description="Rewritten description tailored to the funding agency's vision")
    rationale: str = Field(..., description="Rationale for the scores and rewriting approach")
    experience_rating_facet_a: int = Field(..., ge=1, le=5, description="Facet A: Competency & Capacity (1-5)")
    experience_rating_facet_b: int = Field(..., ge=1, le=5, description="Facet B: Fit with Program Priorities (1-5)")
    experience_rating_facet_c: int = Field(..., ge=1, le=5, description="Facet C: Impact & Value (1-5)")
    experience_rating_facet_d: int = Field(..., ge=1, le=5, description="Facet D: Narrative Flow & Coherence (1-5)")

class ExperienceAnalysisResponse(BaseModel):
    """
    API response model containing an experience and its analysis.
    Used by endpoints that return analyzed experiences to the frontend.
    """
    experience: Experience = Field(..., description="The original experience")
    analysis: StoryTellingResponse = Field(..., description="The analysis/rewritten story")
